<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
           {
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"管理员管理",
                       "menuJump":"列表",
                       "tableName":"users"
                   }
               ],
               "menu":"管理员管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"教师管理",
                       "menuJump":"列表",
                       "tableName":"jiaoshi"
                   }
               ],
               "menu":"教师管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"学生管理",
                       "menuJump":"列表",
                       "tableName":"yonghu"
                   }
               ],
               "menu":"学生管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"实验室信息管理",
                       "menuJump":"列表",
                       "tableName":"shiyanshi"
                   }
               ],
               "menu":"实验室信息管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "审核",
                           "删除"
                       ],
                       "menu":"实验室申请管理",
                       "menuJump":"列表",
                       "tableName":"shiyanshishenqing"
                   }
               ],
               "menu":"实验室申请管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "审核",
                           "删除"
                       ],
                       "menu":"课程信息管理",
                       "menuJump":"列表",
                       "tableName":"kecheng"
                   }
               ],
               "menu":"课程信息管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "审核",
                           "删除"
                       ],
                       "menu":"排课取消申请管理",
                       "menuJump":"列表",
                       "tableName":"paiekequxiao"
                   }
               ],
               "menu":"排课取消申请管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"公告管理",
                       "menuJump":"列表",
                       "tableName":"news"
                   }
               ],
               "menu":"公告管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"班级管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryBanji"
                   }
                   ,
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"第几节管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryJieke"
                   }
                   ,
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"课程类型管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryKecheng"
                   }
                   ,
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"公告类型管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryNews"
                   }
                   ,
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"实验室类型管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryShiyanshi"
                   }
                   ,
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"星期管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryXingqi"
                   }
                   ,
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "删除",
                           "修改"
                       ],
                       "menu":"学期管理",
                       "menuJump":"列表",
                       "tableName":"dictionaryXueqi"
                   }
               ],
               "menu":"基础数据管理"
           }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	      {
	          "child":[
	              {
	                  "buttons":[
	                      "查看",
	                      "新增",
	                      "修改",
	                      "删除"
	                  ],
	                  "menu":"学生管理",
	                  "menuJump":"列表",
	                  "tableName":"yonghu"
	              }
	          ],
	          "menu":"学生管理"
	      }
	      ,{
	          "child":[
	              {
	                  "buttons":[
	                      "查看",
	      				"申请"
	                  ],
	                  "menu":"实验室信息管理",
	                  "menuJump":"列表",
	                  "tableName":"shiyanshi"
	              }
	          ],
	          "menu":"实验室信息管理"
	      }
	      ,{
	          "child":[
	              {
	                  "buttons":[
	                      "查看",
                          "申请",
	                      "删除"
	                  ],
	                  "menu":"实验室申请管理",
	                  "menuJump":"列表",
	                  "tableName":"shiyanshishenqing"
	              }
	          ],
	          "menu":"实验室申请管理"
	      }
	      ,{
	          "child":[
	              {
	                  "buttons":[
	                      "查看",
	                      "新增",
	      				"申请"
	                  ],
	                  "menu":"课程信息管理",
	                  "menuJump":"列表",
	                  "tableName":"kecheng"
	              }
	          ],
	          "menu":"课程信息管理"
	      }
	      ,{
	          "child":[
	              {
	                  "buttons":[
	                      "查看",
	                      "删除"
	                  ],
	                  "menu":"排课取消申请管理",
	                  "menuJump":"列表",
	                  "tableName":"paiekequxiao"
	              }
	          ],
	          "menu":"排课取消申请管理"
	      }
	      ,{
	          "child":[
	              {
	                  "buttons":[
	                      "查看"
	                  ],
	                  "menu":"公告管理",
	                  "menuJump":"列表",
	                  "tableName":"news"
	              }
	          ],
	          "menu":"公告管理"
	      }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	},
	{
	    "backMenu":[
	     {
	         "child":[
	             {
	                 "buttons":[
	                     "查看"
	                 ],
	                 "menu":"实验室信息管理",
	                 "menuJump":"列表",
	                 "tableName":"shiyanshi"
	             }
	         ],
	         "menu":"实验室信息管理"
	     }
	     ,{
	         "child":[
	             {
	                 "buttons":[
	                     "查看"
	                 ],
	                 "menu":"课程信息管理",
	                 "menuJump":"列表",
	                 "tableName":"kecheng"
	             }
	         ],
	         "menu":"课程信息管理"
	     }
	     ,{
	         "child":[
	             {
	                 "buttons":[
	                     "查看"
	                 ],
	                 "menu":"公告管理",
	                 "menuJump":"列表",
	                 "tableName":"news"
	             }
	         ],
	         "menu":"公告管理"
	     }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	},
	
];

var hasMessage = '';
